name: HNG Stage 2 CI
on: [push, pull_request]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install flake8 pytest

      - name: Run Linting
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run Tests
        run: pytest api/tests/

      - name: Build and Run with Compose
        run: |
          docker-compose up -d
          sleep 10
          docker-compose ps

      - name: Cleanup
        if: always()
        run: docker-compose down
